-- ==========================================================================
-- Cambridge subject code -> name mapping.
--
-- Provenance: parsed deterministically (regex over raw HTML, no LLM in the
-- loop) from the official Cambridge International subject indexes:
--   /programmes-and-qualifications/cambridge-upper-secondary/cambridge-igcse/subjects/
--   /programmes-and-qualifications/cambridge-upper-secondary/cambridge-o-level/subjects/
--   /programmes-and-qualifications/cambridge-advanced/cambridge-international-as-and-a-levels/subjects/
-- Level is taken from the URL slug prefix, not the page, because every page
-- carries the same global nav listing all subjects.
--
-- Three legacy codes are appended by hand (is_legacy = true): they appear in
-- past papers but not on the live site. Regenerate by re-scraping; keep the
-- legacy rows.
-- ==========================================================================

insert into subjects (code, name, qualification, is_legacy) values
  ('8001', 'General Paper (legacy, replaced by 8021)', 'AS/A Level', true),
  ('8021', 'General Paper as Level Only', 'AS/A Level', false),
  ('8022', 'Spanish Language', 'AS/A Level', false),
  ('8027', 'German Language', 'AS/A Level', false),
  ('8028', 'French Language', 'AS/A Level', false),
  ('8101', 'History', 'AS/A Level', false),
  ('8102', 'History', 'AS/A Level', false),
  ('8238', 'Chinese Language', 'AS/A Level', false),
  ('8291', 'Environmental Management', 'AS/A Level', false),
  ('8386', 'Sport and Physical Education', 'AS/A Level', false),
  ('8679', 'Afrikaans Language as Level Only', 'AS/A Level', false),
  ('8680', 'Arabic Language as Level Only', 'AS/A Level', false),
  ('8684', 'Portuguese Language as Level Only', 'AS/A Level', false),
  ('8686', 'Urdu Language as Level Only', 'AS/A Level', false),
  ('8689', 'Tamil Language as Level Only', 'AS/A Level', false),
  ('8695', 'English Language and Literature as Level Only', 'AS/A Level', false),
  ('9084', 'Law', 'AS/A Level', false),
  ('9093', 'English Language', 'AS/A Level', false),
  ('9231', 'Mathematics Further', 'AS/A Level', false),
  ('9239', 'Global Perspectives and Research', 'AS/A Level', false),
  ('9274', 'Classical Studies', 'AS/A Level', false),
  ('9395', 'Travel and Tourism', 'AS/A Level', false),
  ('9479', 'Art and Design', 'AS/A Level', false),
  ('9481', 'Digital Media Design', 'AS/A Level', false),
  ('9482', 'Drama', 'AS/A Level', false),
  ('9483', 'Music', 'AS/A Level', false),
  ('9484', 'Biblical Studies', 'AS/A Level', false),
  ('9487', 'Hinduism', 'AS/A Level', false),
  ('9488', 'Islamic Studies', 'AS/A Level', false),
  ('9489', 'History', 'AS/A Level', false),
  ('9607', 'Media Studies', 'AS/A Level', false),
  ('9608', 'Computer Science (withdrawn 2021, replaced by 9618)', 'AS/A Level', true),
  ('9609', 'Business', 'AS/A Level', false),
  ('9618', 'Computer Science', 'AS/A Level', false),
  ('9626', 'Information Technology', 'AS/A Level', false),
  ('9680', 'Arabic', 'AS/A Level', false),
  ('9686', 'Urdu Pakistan Only', 'AS/A Level', false),
  ('9689', 'Tamil', 'AS/A Level', false),
  ('9693', 'Marine Science', 'AS/A Level', false),
  ('9694', 'Thinking Skills', 'AS/A Level', false),
  ('9695', 'English Literature', 'AS/A Level', false),
  ('9696', 'Geography', 'AS/A Level', false),
  ('9699', 'Sociology', 'AS/A Level', false),
  ('9700', 'Biology', 'AS/A Level', false),
  ('9701', 'Chemistry', 'AS/A Level', false),
  ('9702', 'Physics', 'AS/A Level', false),
  ('9705', 'Design and Technology', 'AS/A Level', false),
  ('9706', 'Accounting', 'AS/A Level', false),
  ('9708', 'Economics', 'AS/A Level', false),
  ('9709', 'Mathematics', 'AS/A Level', false),
  ('9718', 'Portuguese', 'AS/A Level', false),
  ('9844', 'Spanish Language and Literature', 'AS/A Level', false),
  ('9866', 'Urdu Language Literature', 'AS/A Level', false),
  ('9868', 'Chinese Language and Literature', 'AS/A Level', false),
  ('9897', 'German', 'AS/A Level', false),
  ('9898', 'French Language Literature', 'AS/A Level', false),
  ('9981', 'History', 'AS/A Level', false),
  ('9982', 'History', 'AS/A Level', false),
  ('9990', 'Psychology', 'AS/A Level', false),
  ('0262', 'Swahili', 'IGCSE', false),
  ('0264', 'Business', 'IGCSE', false),
  ('0266', 'Psychology', 'IGCSE', false),
  ('0400', 'Art and Design', 'IGCSE', false),
  ('0408', 'World Literature', 'IGCSE', false),
  ('0409', 'History American us', 'IGCSE', false),
  ('0410', 'Music', 'IGCSE', false),
  ('0411', 'Drama', 'IGCSE', false),
  ('0413', 'Physical Education', 'IGCSE', false),
  ('0417', 'Information and Communication Technology', 'IGCSE', false),
  ('0444', 'Mathematics us', 'IGCSE', false),
  ('0445', 'Design and Technology', 'IGCSE', false),
  ('0448', 'Pakistan Studies', 'IGCSE', false),
  ('0450', 'Business Studies', 'IGCSE', false),
  ('0452', 'Accounting', 'IGCSE', false),
  ('0454', 'Enterprise', 'IGCSE', false),
  ('0455', 'Economics', 'IGCSE', false),
  ('0457', 'Global Perspectives', 'IGCSE', false),
  ('0460', 'Geography', 'IGCSE', false),
  ('0465', 'Core English as Second Language', 'IGCSE', false),
  ('0470', 'History', 'IGCSE', false),
  ('0471', 'Travel and Tourism', 'IGCSE', false),
  ('0472', 'English as An Additional Language', 'IGCSE', false),
  ('0474', 'Literature In Spanish', 'IGCSE', false),
  ('0475', 'Literature in English', 'IGCSE', true),
  ('0478', 'Computer Science', 'IGCSE', false),
  ('0479', 'Statistics', 'IGCSE', false),
  ('0480', 'Latin', 'IGCSE', false),
  ('0490', 'Religious Studies', 'IGCSE', false),
  ('0493', 'Islamiyat', 'IGCSE', false),
  ('0495', 'Sociology', 'IGCSE', false),
  ('0499', 'Sanskrit', 'IGCSE', false),
  ('0500', 'English First Language', 'IGCSE', false),
  ('0501', 'French First Language', 'IGCSE', false),
  ('0502', 'Spanish First Language', 'IGCSE', false),
  ('0504', 'Portuguese First Language', 'IGCSE', false),
  ('0505', 'German First Language', 'IGCSE', false),
  ('0508', 'Arabic First Language', 'IGCSE', false),
  ('0509', 'Chinese First Language', 'IGCSE', false),
  ('0510', 'English Second Language Oral Endorsement', 'IGCSE', false),
  ('0511', 'English Second Language Count In Oral', 'IGCSE', false),
  ('0513', 'Turkish First Language', 'IGCSE', false),
  ('0518', 'Thai First Language', 'IGCSE', false),
  ('0520', 'French Foreign Language', 'IGCSE', false),
  ('0523', 'Chinese Second Language', 'IGCSE', false),
  ('0524', 'English First Language us', 'IGCSE', false),
  ('0525', 'German Foreign Language', 'IGCSE', false),
  ('0530', 'Spanish Foreign Language', 'IGCSE', false),
  ('0531', 'Isizulu as a Second Language', 'IGCSE', false),
  ('0535', 'Italian Foreign Language', 'IGCSE', false),
  ('0538', 'Bahasa Indonesia', 'IGCSE', false),
  ('0539', 'Urdu as a Second Language', 'IGCSE', false),
  ('0544', 'Arabic Foreign Language', 'IGCSE', false),
  ('0546', 'Malay Foreign Language', 'IGCSE', false),
  ('0547', 'Chinese Mandarin Foreign Language', 'IGCSE', false),
  ('0548', 'Afrikaans Second Language', 'IGCSE', false),
  ('0549', 'Hindi as a Second Language', 'IGCSE', false),
  ('0580', 'Mathematics', 'IGCSE', false),
  ('0600', 'Agriculture', 'IGCSE', false),
  ('0606', 'Mathematics Additional', 'IGCSE', false),
  ('0607', 'International Mathematics', 'IGCSE', false),
  ('0610', 'Biology', 'IGCSE', false),
  ('0620', 'Chemistry', 'IGCSE', false),
  ('0625', 'Physics', 'IGCSE', false),
  ('0648', 'Food and Nutrition', 'IGCSE', false),
  ('0652', 'Physical Science', 'IGCSE', false),
  ('0653', 'Science Combined', 'IGCSE', false),
  ('0654', 'Sciences Co Ordinated Double', 'IGCSE', false),
  ('0680', 'Environmental Management', 'IGCSE', false),
  ('0695', 'Vietnamese', 'IGCSE', false),
  ('0696', 'Malay', 'IGCSE', false),
  ('0697', 'Marine Science', 'IGCSE', false),
  ('0698', 'Setswana', 'IGCSE', false),
  ('0715', 'Commerce', 'IGCSE', false),
  ('0716', 'Japanese', 'IGCSE', false),
  ('0772', 'English as An Additional Language 9 1', 'IGCSE', false),
  ('0774', 'Business 9 1', 'IGCSE', false),
  ('0970', 'Biology 9 1', 'IGCSE', false),
  ('0971', 'Chemistry 9 1', 'IGCSE', false),
  ('0972', 'Physics 9 1', 'IGCSE', false),
  ('0973', 'Sciences (9 1) Only', 'IGCSE', false),
  ('0976', 'Geography 9 1', 'IGCSE', false),
  ('0977', 'History 9 1', 'IGCSE', false),
  ('0978', 'Music 9 1', 'IGCSE', false),
  ('0979', 'Design and Technology 9 1', 'IGCSE', false),
  ('0980', 'Mathematics 9 1', 'IGCSE', false),
  ('0983', 'Information and Communication Technology 9 1', 'IGCSE', false),
  ('0984', '9 1 Computer Science', 'IGCSE', false),
  ('0985', 'Accounting 9 1', 'IGCSE', false),
  ('0986', 'Business Studies 9 1', 'IGCSE', false),
  ('0987', 'Economics 9 1', 'IGCSE', false),
  ('0989', 'Art and Design 9 1', 'IGCSE', false),
  ('0990', '9 1 First Language English', 'IGCSE', false),
  ('0992', 'English Literature', 'IGCSE', false),
  ('0993', 'English Second Language Speaking Endorsement 9 1', 'IGCSE', false),
  ('0994', 'Drama 9 1', 'IGCSE', false),
  ('0995', 'Physical Education', 'IGCSE', false),
  ('7156', 'French 9 1', 'IGCSE', false),
  ('7159', 'German 9 1', 'IGCSE', false),
  ('7160', 'Spanish 9 1', 'IGCSE', false),
  ('7164', 'Italian 9 1', 'IGCSE', false),
  ('7180', 'Arabic 9 1', 'IGCSE', false),
  ('7184', 'Arabic (9 1) First Language', 'IGCSE', false),
  ('1123', 'English Language', 'O Level', false),
  ('2010', 'Literature In English', 'O Level', false),
  ('2035', 'Biblical Studies', 'O Level', false),
  ('2058', 'Islamiyat', 'O Level', false),
  ('2059', 'Pakistan Studies', 'O Level', false),
  ('2068', 'Islamic Studies', 'O Level', false),
  ('2069', 'Global Perspectives', 'O Level', false),
  ('2147', 'History', 'O Level', false),
  ('2210', 'Computer Science', 'O Level', false),
  ('2217', 'Geography', 'O Level', false),
  ('2251', 'Sociology', 'O Level', false),
  ('2281', 'Economics', 'O Level', false),
  ('3180', 'Arabic', 'O Level', false),
  ('3204', 'Bengali', 'O Level', false),
  ('3205', 'Sinhala', 'O Level', false),
  ('3226', 'Tamil', 'O Level', false),
  ('3247', 'Urdu First Language', 'O Level', false),
  ('3248', 'Urdu Second Language', 'O Level', false),
  ('4024', 'Mathematics D', 'O Level', false),
  ('4037', 'Mathematics Additional', 'O Level', false),
  ('4040', 'Statistics', 'O Level', false),
  ('5014', 'Environmental Management', 'O Level', false),
  ('5054', 'Physics', 'O Level', false),
  ('5070', 'Chemistry', 'O Level', false),
  ('5090', 'Biology', 'O Level', false),
  ('5129', 'Science Combined', 'O Level', false),
  ('6065', 'Food and Nutrition', 'O Level', false),
  ('6090', 'Art and Design', 'O Level', false),
  ('6130', 'Fashion and Textiles', 'O Level', false),
  ('7081', 'Business', 'O Level', false),
  ('7094', 'Bangladesh Studies', 'O Level', false),
  ('7100', 'Commerce', 'O Level', false),
  ('7115', 'Business Studies', 'O Level', false),
  ('7707', 'Accounting', 'O Level', false)
on conflict (code) do update
  set name = excluded.name,
      qualification = excluded.qualification,
      is_legacy = excluded.is_legacy;
