// ==========================================================================
// Cambridge subject code -> name, for client-side display without a round trip.
// Mirrors supabase/seeds/seed_subjects.sql; both come from the same scrape of the
// official Cambridge International subject indexes (parsed by regex, no LLM).
// The `subjects` table is the source of truth; this is a display convenience.
// ==========================================================================

export type Qualification = 'IGCSE' | 'O Level' | 'AS/A Level';

export interface SubjectInfo {
  name: string;
  qualification: Qualification;
  isLegacy: boolean;
}

export const SUBJECT_CODES: Record<string, SubjectInfo> = {
  '8001': { name: 'General Paper (legacy, replaced by 8021)', qualification: 'AS/A Level', isLegacy: true },
  '8021': { name: 'General Paper as Level Only', qualification: 'AS/A Level', isLegacy: false },
  '8022': { name: 'Spanish Language', qualification: 'AS/A Level', isLegacy: false },
  '8027': { name: 'German Language', qualification: 'AS/A Level', isLegacy: false },
  '8028': { name: 'French Language', qualification: 'AS/A Level', isLegacy: false },
  '8101': { name: 'History', qualification: 'AS/A Level', isLegacy: false },
  '8102': { name: 'History', qualification: 'AS/A Level', isLegacy: false },
  '8238': { name: 'Chinese Language', qualification: 'AS/A Level', isLegacy: false },
  '8291': { name: 'Environmental Management', qualification: 'AS/A Level', isLegacy: false },
  '8386': { name: 'Sport and Physical Education', qualification: 'AS/A Level', isLegacy: false },
  '8679': { name: 'Afrikaans Language as Level Only', qualification: 'AS/A Level', isLegacy: false },
  '8680': { name: 'Arabic Language as Level Only', qualification: 'AS/A Level', isLegacy: false },
  '8684': { name: 'Portuguese Language as Level Only', qualification: 'AS/A Level', isLegacy: false },
  '8686': { name: 'Urdu Language as Level Only', qualification: 'AS/A Level', isLegacy: false },
  '8689': { name: 'Tamil Language as Level Only', qualification: 'AS/A Level', isLegacy: false },
  '8695': { name: 'English Language and Literature as Level Only', qualification: 'AS/A Level', isLegacy: false },
  '9084': { name: 'Law', qualification: 'AS/A Level', isLegacy: false },
  '9093': { name: 'English Language', qualification: 'AS/A Level', isLegacy: false },
  '9231': { name: 'Mathematics Further', qualification: 'AS/A Level', isLegacy: false },
  '9239': { name: 'Global Perspectives and Research', qualification: 'AS/A Level', isLegacy: false },
  '9274': { name: 'Classical Studies', qualification: 'AS/A Level', isLegacy: false },
  '9395': { name: 'Travel and Tourism', qualification: 'AS/A Level', isLegacy: false },
  '9479': { name: 'Art and Design', qualification: 'AS/A Level', isLegacy: false },
  '9481': { name: 'Digital Media Design', qualification: 'AS/A Level', isLegacy: false },
  '9482': { name: 'Drama', qualification: 'AS/A Level', isLegacy: false },
  '9483': { name: 'Music', qualification: 'AS/A Level', isLegacy: false },
  '9484': { name: 'Biblical Studies', qualification: 'AS/A Level', isLegacy: false },
  '9487': { name: 'Hinduism', qualification: 'AS/A Level', isLegacy: false },
  '9488': { name: 'Islamic Studies', qualification: 'AS/A Level', isLegacy: false },
  '9489': { name: 'History', qualification: 'AS/A Level', isLegacy: false },
  '9607': { name: 'Media Studies', qualification: 'AS/A Level', isLegacy: false },
  '9608': { name: 'Computer Science (withdrawn 2021, replaced by 9618)', qualification: 'AS/A Level', isLegacy: true },
  '9609': { name: 'Business', qualification: 'AS/A Level', isLegacy: false },
  '9618': { name: 'Computer Science', qualification: 'AS/A Level', isLegacy: false },
  '9626': { name: 'Information Technology', qualification: 'AS/A Level', isLegacy: false },
  '9680': { name: 'Arabic', qualification: 'AS/A Level', isLegacy: false },
  '9686': { name: 'Urdu Pakistan Only', qualification: 'AS/A Level', isLegacy: false },
  '9689': { name: 'Tamil', qualification: 'AS/A Level', isLegacy: false },
  '9693': { name: 'Marine Science', qualification: 'AS/A Level', isLegacy: false },
  '9694': { name: 'Thinking Skills', qualification: 'AS/A Level', isLegacy: false },
  '9695': { name: 'English Literature', qualification: 'AS/A Level', isLegacy: false },
  '9696': { name: 'Geography', qualification: 'AS/A Level', isLegacy: false },
  '9699': { name: 'Sociology', qualification: 'AS/A Level', isLegacy: false },
  '9700': { name: 'Biology', qualification: 'AS/A Level', isLegacy: false },
  '9701': { name: 'Chemistry', qualification: 'AS/A Level', isLegacy: false },
  '9702': { name: 'Physics', qualification: 'AS/A Level', isLegacy: false },
  '9705': { name: 'Design and Technology', qualification: 'AS/A Level', isLegacy: false },
  '9706': { name: 'Accounting', qualification: 'AS/A Level', isLegacy: false },
  '9708': { name: 'Economics', qualification: 'AS/A Level', isLegacy: false },
  '9709': { name: 'Mathematics', qualification: 'AS/A Level', isLegacy: false },
  '9718': { name: 'Portuguese', qualification: 'AS/A Level', isLegacy: false },
  '9844': { name: 'Spanish Language and Literature', qualification: 'AS/A Level', isLegacy: false },
  '9866': { name: 'Urdu Language Literature', qualification: 'AS/A Level', isLegacy: false },
  '9868': { name: 'Chinese Language and Literature', qualification: 'AS/A Level', isLegacy: false },
  '9897': { name: 'German', qualification: 'AS/A Level', isLegacy: false },
  '9898': { name: 'French Language Literature', qualification: 'AS/A Level', isLegacy: false },
  '9981': { name: 'History', qualification: 'AS/A Level', isLegacy: false },
  '9982': { name: 'History', qualification: 'AS/A Level', isLegacy: false },
  '9990': { name: 'Psychology', qualification: 'AS/A Level', isLegacy: false },
  '0262': { name: 'Swahili', qualification: 'IGCSE', isLegacy: false },
  '0264': { name: 'Business', qualification: 'IGCSE', isLegacy: false },
  '0266': { name: 'Psychology', qualification: 'IGCSE', isLegacy: false },
  '0400': { name: 'Art and Design', qualification: 'IGCSE', isLegacy: false },
  '0408': { name: 'World Literature', qualification: 'IGCSE', isLegacy: false },
  '0409': { name: 'History American us', qualification: 'IGCSE', isLegacy: false },
  '0410': { name: 'Music', qualification: 'IGCSE', isLegacy: false },
  '0411': { name: 'Drama', qualification: 'IGCSE', isLegacy: false },
  '0413': { name: 'Physical Education', qualification: 'IGCSE', isLegacy: false },
  '0417': { name: 'Information and Communication Technology', qualification: 'IGCSE', isLegacy: false },
  '0444': { name: 'Mathematics us', qualification: 'IGCSE', isLegacy: false },
  '0445': { name: 'Design and Technology', qualification: 'IGCSE', isLegacy: false },
  '0448': { name: 'Pakistan Studies', qualification: 'IGCSE', isLegacy: false },
  '0450': { name: 'Business Studies', qualification: 'IGCSE', isLegacy: false },
  '0452': { name: 'Accounting', qualification: 'IGCSE', isLegacy: false },
  '0454': { name: 'Enterprise', qualification: 'IGCSE', isLegacy: false },
  '0455': { name: 'Economics', qualification: 'IGCSE', isLegacy: false },
  '0457': { name: 'Global Perspectives', qualification: 'IGCSE', isLegacy: false },
  '0460': { name: 'Geography', qualification: 'IGCSE', isLegacy: false },
  '0465': { name: 'Core English as Second Language', qualification: 'IGCSE', isLegacy: false },
  '0470': { name: 'History', qualification: 'IGCSE', isLegacy: false },
  '0471': { name: 'Travel and Tourism', qualification: 'IGCSE', isLegacy: false },
  '0472': { name: 'English as An Additional Language', qualification: 'IGCSE', isLegacy: false },
  '0474': { name: 'Literature In Spanish', qualification: 'IGCSE', isLegacy: false },
  '0475': { name: 'Literature in English', qualification: 'IGCSE', isLegacy: true },
  '0478': { name: 'Computer Science', qualification: 'IGCSE', isLegacy: false },
  '0479': { name: 'Statistics', qualification: 'IGCSE', isLegacy: false },
  '0480': { name: 'Latin', qualification: 'IGCSE', isLegacy: false },
  '0490': { name: 'Religious Studies', qualification: 'IGCSE', isLegacy: false },
  '0493': { name: 'Islamiyat', qualification: 'IGCSE', isLegacy: false },
  '0495': { name: 'Sociology', qualification: 'IGCSE', isLegacy: false },
  '0499': { name: 'Sanskrit', qualification: 'IGCSE', isLegacy: false },
  '0500': { name: 'English First Language', qualification: 'IGCSE', isLegacy: false },
  '0501': { name: 'French First Language', qualification: 'IGCSE', isLegacy: false },
  '0502': { name: 'Spanish First Language', qualification: 'IGCSE', isLegacy: false },
  '0504': { name: 'Portuguese First Language', qualification: 'IGCSE', isLegacy: false },
  '0505': { name: 'German First Language', qualification: 'IGCSE', isLegacy: false },
  '0508': { name: 'Arabic First Language', qualification: 'IGCSE', isLegacy: false },
  '0509': { name: 'Chinese First Language', qualification: 'IGCSE', isLegacy: false },
  '0510': { name: 'English Second Language Oral Endorsement', qualification: 'IGCSE', isLegacy: false },
  '0511': { name: 'English Second Language Count In Oral', qualification: 'IGCSE', isLegacy: false },
  '0513': { name: 'Turkish First Language', qualification: 'IGCSE', isLegacy: false },
  '0518': { name: 'Thai First Language', qualification: 'IGCSE', isLegacy: false },
  '0520': { name: 'French Foreign Language', qualification: 'IGCSE', isLegacy: false },
  '0523': { name: 'Chinese Second Language', qualification: 'IGCSE', isLegacy: false },
  '0524': { name: 'English First Language us', qualification: 'IGCSE', isLegacy: false },
  '0525': { name: 'German Foreign Language', qualification: 'IGCSE', isLegacy: false },
  '0530': { name: 'Spanish Foreign Language', qualification: 'IGCSE', isLegacy: false },
  '0531': { name: 'Isizulu as a Second Language', qualification: 'IGCSE', isLegacy: false },
  '0535': { name: 'Italian Foreign Language', qualification: 'IGCSE', isLegacy: false },
  '0538': { name: 'Bahasa Indonesia', qualification: 'IGCSE', isLegacy: false },
  '0539': { name: 'Urdu as a Second Language', qualification: 'IGCSE', isLegacy: false },
  '0544': { name: 'Arabic Foreign Language', qualification: 'IGCSE', isLegacy: false },
  '0546': { name: 'Malay Foreign Language', qualification: 'IGCSE', isLegacy: false },
  '0547': { name: 'Chinese Mandarin Foreign Language', qualification: 'IGCSE', isLegacy: false },
  '0548': { name: 'Afrikaans Second Language', qualification: 'IGCSE', isLegacy: false },
  '0549': { name: 'Hindi as a Second Language', qualification: 'IGCSE', isLegacy: false },
  '0580': { name: 'Mathematics', qualification: 'IGCSE', isLegacy: false },
  '0600': { name: 'Agriculture', qualification: 'IGCSE', isLegacy: false },
  '0606': { name: 'Mathematics Additional', qualification: 'IGCSE', isLegacy: false },
  '0607': { name: 'International Mathematics', qualification: 'IGCSE', isLegacy: false },
  '0610': { name: 'Biology', qualification: 'IGCSE', isLegacy: false },
  '0620': { name: 'Chemistry', qualification: 'IGCSE', isLegacy: false },
  '0625': { name: 'Physics', qualification: 'IGCSE', isLegacy: false },
  '0648': { name: 'Food and Nutrition', qualification: 'IGCSE', isLegacy: false },
  '0652': { name: 'Physical Science', qualification: 'IGCSE', isLegacy: false },
  '0653': { name: 'Science Combined', qualification: 'IGCSE', isLegacy: false },
  '0654': { name: 'Sciences Co Ordinated Double', qualification: 'IGCSE', isLegacy: false },
  '0680': { name: 'Environmental Management', qualification: 'IGCSE', isLegacy: false },
  '0695': { name: 'Vietnamese', qualification: 'IGCSE', isLegacy: false },
  '0696': { name: 'Malay', qualification: 'IGCSE', isLegacy: false },
  '0697': { name: 'Marine Science', qualification: 'IGCSE', isLegacy: false },
  '0698': { name: 'Setswana', qualification: 'IGCSE', isLegacy: false },
  '0715': { name: 'Commerce', qualification: 'IGCSE', isLegacy: false },
  '0716': { name: 'Japanese', qualification: 'IGCSE', isLegacy: false },
  '0772': { name: 'English as An Additional Language 9 1', qualification: 'IGCSE', isLegacy: false },
  '0774': { name: 'Business 9 1', qualification: 'IGCSE', isLegacy: false },
  '0970': { name: 'Biology 9 1', qualification: 'IGCSE', isLegacy: false },
  '0971': { name: 'Chemistry 9 1', qualification: 'IGCSE', isLegacy: false },
  '0972': { name: 'Physics 9 1', qualification: 'IGCSE', isLegacy: false },
  '0973': { name: 'Sciences (9 1) Only', qualification: 'IGCSE', isLegacy: false },
  '0976': { name: 'Geography 9 1', qualification: 'IGCSE', isLegacy: false },
  '0977': { name: 'History 9 1', qualification: 'IGCSE', isLegacy: false },
  '0978': { name: 'Music 9 1', qualification: 'IGCSE', isLegacy: false },
  '0979': { name: 'Design and Technology 9 1', qualification: 'IGCSE', isLegacy: false },
  '0980': { name: 'Mathematics 9 1', qualification: 'IGCSE', isLegacy: false },
  '0983': { name: 'Information and Communication Technology 9 1', qualification: 'IGCSE', isLegacy: false },
  '0984': { name: '9 1 Computer Science', qualification: 'IGCSE', isLegacy: false },
  '0985': { name: 'Accounting 9 1', qualification: 'IGCSE', isLegacy: false },
  '0986': { name: 'Business Studies 9 1', qualification: 'IGCSE', isLegacy: false },
  '0987': { name: 'Economics 9 1', qualification: 'IGCSE', isLegacy: false },
  '0989': { name: 'Art and Design 9 1', qualification: 'IGCSE', isLegacy: false },
  '0990': { name: '9 1 First Language English', qualification: 'IGCSE', isLegacy: false },
  '0992': { name: 'English Literature', qualification: 'IGCSE', isLegacy: false },
  '0993': { name: 'English Second Language Speaking Endorsement 9 1', qualification: 'IGCSE', isLegacy: false },
  '0994': { name: 'Drama 9 1', qualification: 'IGCSE', isLegacy: false },
  '0995': { name: 'Physical Education', qualification: 'IGCSE', isLegacy: false },
  '7156': { name: 'French 9 1', qualification: 'IGCSE', isLegacy: false },
  '7159': { name: 'German 9 1', qualification: 'IGCSE', isLegacy: false },
  '7160': { name: 'Spanish 9 1', qualification: 'IGCSE', isLegacy: false },
  '7164': { name: 'Italian 9 1', qualification: 'IGCSE', isLegacy: false },
  '7180': { name: 'Arabic 9 1', qualification: 'IGCSE', isLegacy: false },
  '7184': { name: 'Arabic (9 1) First Language', qualification: 'IGCSE', isLegacy: false },
  '1123': { name: 'English Language', qualification: 'O Level', isLegacy: false },
  '2010': { name: 'Literature In English', qualification: 'O Level', isLegacy: false },
  '2035': { name: 'Biblical Studies', qualification: 'O Level', isLegacy: false },
  '2058': { name: 'Islamiyat', qualification: 'O Level', isLegacy: false },
  '2059': { name: 'Pakistan Studies', qualification: 'O Level', isLegacy: false },
  '2068': { name: 'Islamic Studies', qualification: 'O Level', isLegacy: false },
  '2069': { name: 'Global Perspectives', qualification: 'O Level', isLegacy: false },
  '2147': { name: 'History', qualification: 'O Level', isLegacy: false },
  '2210': { name: 'Computer Science', qualification: 'O Level', isLegacy: false },
  '2217': { name: 'Geography', qualification: 'O Level', isLegacy: false },
  '2251': { name: 'Sociology', qualification: 'O Level', isLegacy: false },
  '2281': { name: 'Economics', qualification: 'O Level', isLegacy: false },
  '3180': { name: 'Arabic', qualification: 'O Level', isLegacy: false },
  '3204': { name: 'Bengali', qualification: 'O Level', isLegacy: false },
  '3205': { name: 'Sinhala', qualification: 'O Level', isLegacy: false },
  '3226': { name: 'Tamil', qualification: 'O Level', isLegacy: false },
  '3247': { name: 'Urdu First Language', qualification: 'O Level', isLegacy: false },
  '3248': { name: 'Urdu Second Language', qualification: 'O Level', isLegacy: false },
  '4024': { name: 'Mathematics D', qualification: 'O Level', isLegacy: false },
  '4037': { name: 'Mathematics Additional', qualification: 'O Level', isLegacy: false },
  '4040': { name: 'Statistics', qualification: 'O Level', isLegacy: false },
  '5014': { name: 'Environmental Management', qualification: 'O Level', isLegacy: false },
  '5054': { name: 'Physics', qualification: 'O Level', isLegacy: false },
  '5070': { name: 'Chemistry', qualification: 'O Level', isLegacy: false },
  '5090': { name: 'Biology', qualification: 'O Level', isLegacy: false },
  '5129': { name: 'Science Combined', qualification: 'O Level', isLegacy: false },
  '6065': { name: 'Food and Nutrition', qualification: 'O Level', isLegacy: false },
  '6090': { name: 'Art and Design', qualification: 'O Level', isLegacy: false },
  '6130': { name: 'Fashion and Textiles', qualification: 'O Level', isLegacy: false },
  '7081': { name: 'Business', qualification: 'O Level', isLegacy: false },
  '7094': { name: 'Bangladesh Studies', qualification: 'O Level', isLegacy: false },
  '7100': { name: 'Commerce', qualification: 'O Level', isLegacy: false },
  '7115': { name: 'Business Studies', qualification: 'O Level', isLegacy: false },
  '7707': { name: 'Accounting', qualification: 'O Level', isLegacy: false },
};

// subject code is the first underscore-delimited field of a paper schema
// string, e.g. '0625_s25_22' -> '0625'. The string stays ground truth.
export function subjectCodeFromSchema(schema: string): string {
  return schema.split('_')[0] ?? '';
}

// display name for a schema string, falling back to the bare code so an
// unknown/new syllabus still renders something meaningful.
export function subjectNameFromSchema(schema: string): string {
  const code = subjectCodeFromSchema(schema);
  return SUBJECT_CODES[code]?.name ?? code;
}
