// ==========================================================================
//
// TypeScript mirror of schema.sql.
//
// Every writer in src/lib/supabase/ previously took `supabase: any` and built
// untyped object literals, so a misspelled column or a wrong unit was a
// runtime surprise from Postgres rather than a compile error. These types make
// the table shape explicit at the call site.
//
// CONVENTION
//   <Table>Row     - a row as it comes back from a select (all columns present)
//   <Table>Insert  - what a client is allowed to send (server-owned and
//                    generated columns omitted, defaulted columns optional)
//
// Columns marked SERVER-OWNED are deliberately absent from the Insert type:
// they are set by a trigger or generated by Postgres, and a client that tries
// to send them should fail to compile.
//
// This file is hand-written from schema.sql rather than generated by the
// Supabase CLI (`supabase gen types typescript`), because the CLI needs a
// running database and there is none in this environment. If you later wire
// the CLI up, prefer its output and delete this file.
// ==========================================================================

import type { SupabaseClient } from '@supabase/supabase-js';
import type {
  AttemptStatus,
  ExamSeries,
  GoalKind,
  Qualification,
} from './enums';

/**
 * The Supabase client, as used across src/lib/supabase/.
 * Aliased so the generic parameter can be filled in later (once generated
 * types exist) by changing one line instead of every signature.
 */
export type Db = SupabaseClient;

/** A Cambridge paper schema string, e.g. '0625_s25_22'. */
export type PaperSchema = string;

/** A Cambridge subject code, e.g. '0625'. */
export type SubjectCode = string;

/** ISO-8601 timestamp string, as Postgres timestamptz round-trips it. */
export type IsoTimestamp = string;

/** Calendar date as 'YYYY-MM-DD'. */
export type IsoDate = string;

// --------------------------------------------------------------------------
// Reference data
// --------------------------------------------------------------------------

export interface SubjectRow {
  code: SubjectCode;
  name: string;
  qualification: Qualification;
  is_legacy: boolean;
  created_at: IsoTimestamp;
}

export interface TopicRow {
  id: string;
  subject_code: SubjectCode;
  /** Stable within a subject, e.g. '4.1'. */
  code: string;
  name: string;
  parent_code: string | null;
  sort_order: number;
}

export type TopicInsert = Omit<TopicRow, 'id'>;

export interface PaperAnswerKeyRow {
  paper_id: PaperSchema;
  source_url: string | null;
  question_count: number | null;
  parsed_at: IsoTimestamp;
}

export type PaperAnswerKeyInsert = Omit<PaperAnswerKeyRow, 'parsed_at'> &
  Partial<Pick<PaperAnswerKeyRow, 'parsed_at'>>;

export interface PaperAnswerRow {
  paper_id: PaperSchema;
  question_number: number;
  /** 0 = A, 1 = B, ... Index into OPTION_LETTERS. */
  correct_option: number;
  option_count: number;
  marks: number;
  topic_id: string | null;
}

export type PaperAnswerInsert = Omit<PaperAnswerRow, 'option_count' | 'marks' | 'topic_id'> &
  Partial<Pick<PaperAnswerRow, 'option_count' | 'marks' | 'topic_id'>>;

// --------------------------------------------------------------------------
// Users
// --------------------------------------------------------------------------

export interface ProfileRow {
  id: string;
  display_name: string | null;
  /** IANA zone, e.g. 'Asia/Kolkata'. */
  timezone: string;
  created_at: IsoTimestamp;
}

// --------------------------------------------------------------------------
// Attempts
// --------------------------------------------------------------------------

export interface ExamAttemptRow {
  id: string;
  user_id: string;
  /** Ground truth. The five fields below are GENERATED from this by Postgres. */
  paper_id: PaperSchema;

  subject_code: SubjectCode; // SERVER-OWNED (generated)
  series: ExamSeries;        // SERVER-OWNED (generated)
  exam_year: number;         // SERVER-OWNED (generated)
  paper_number: number | null; // SERVER-OWNED (generated)
  variant: number | null;      // SERVER-OWNED (generated)

  status: AttemptStatus;
  started_at: IsoTimestamp;
  finished_at: IsoTimestamp | null;
  /** Milliseconds. */
  duration_ms: number | null;

  questions_total: number | null;
  questions_answered: number;

  client_timezone: string;
  local_date: IsoDate;

  metrics_version: number;
  created_at: IsoTimestamp;
}

/** What startExamAttempt() sends when opening an attempt. */
export interface ExamAttemptInsert {
  user_id: string;
  paper_id: PaperSchema;
  status: AttemptStatus;
  started_at: IsoTimestamp;
  client_timezone: string;
  local_date: IsoDate;
  questions_total?: number;
}

/** What finishExamAttempt() sends when closing one. */
export interface ExamAttemptFinish {
  status: AttemptStatus;
  finished_at: IsoTimestamp;
  questions_answered: number;
  duration_ms?: number;
}

export interface QuestionAttemptRow {
  id: string;
  exam_attempt_id: string;
  question_number: number;

  /** 0 = A, 1 = B, ... null = unanswered. */
  selected_option: number | null;
  /** Bitmask: bit i set means option i was ruled out. */
  eliminated_mask: number;

  /**
   * SERVER-OWNED. Set by the set_question_correctness() trigger from the
   * cached answer key. Never sent by the client - that is the whole point.
   * null = no key cached yet, or unanswered.
   */
  is_correct: boolean | null;

  /** Milliseconds. */
  time_spent_ms: number;
  /** Milliseconds before the first meaningful action. */
  hesitation_ms: number | null;

  option_switch_count: number;
  elimination_reversal_count: number;
  revisit_count: number;

  marked_for_review_count: number;
  marked_as_difficult_count: number;
  marked_for_save_count: number;

  stable_elimination_ratio: number;
  exploration_depth: number;
  exploration_breadth: number;

  created_at: IsoTimestamp;
}

/** Note the absence of is_correct - it cannot be sent, by design. */
export type QuestionAttemptInsert = Omit<
  QuestionAttemptRow,
  'id' | 'is_correct' | 'created_at'
>;

/** Just enough of a written row to map ids back to question numbers. */
export type QuestionAttemptRef = Pick<QuestionAttemptRow, 'id' | 'question_number'>;

export interface QuestionMetricsRow {
  question_attempt_id: string;
  metrics_version: number;
  /** All three are 0..1. */
  confidence: number;
  difficulty: number;
  interest: number;
  computed_at: IsoTimestamp;
}

export type QuestionMetricsInsert = Omit<QuestionMetricsRow, 'computed_at'>;

export interface AttemptEventRow {
  id: number;
  exam_attempt_id: string;
  /** Client ordinal; breaks ties when two events share a millisecond. */
  seq: number;
  question_number: number | null;
  element_type: string;
  action_type: string;
  option_index: number | null;
  /** Milliseconds since exam start. */
  elapsed_ms: number;
  occurred_at: IsoTimestamp;
}

export type AttemptEventInsert = Omit<AttemptEventRow, 'id'>;

export interface GoalRow {
  id: string;
  user_id: string;
  kind: GoalKind;
  subject_code: SubjectCode | null;
  target: number;
  active: boolean;
  created_at: IsoTimestamp;
}

export type GoalInsert = Omit<GoalRow, 'id' | 'created_at' | 'active'> &
  Partial<Pick<GoalRow, 'active'>>;

// --------------------------------------------------------------------------
// Views (read-only)
// --------------------------------------------------------------------------

export interface AttemptSummaryView {
  id: string;
  user_id: string;
  paper_id: PaperSchema;
  status: AttemptStatus;
  subject_code: SubjectCode;
  subject_name: string | null;
  qualification: Qualification | null;
  series: ExamSeries;
  exam_year: number;
  paper_number: number | null;
  variant: number | null;
  started_at: IsoTimestamp;
  finished_at: IsoTimestamp | null;
  duration_ms: number | null;
  local_date: IsoDate;
  client_timezone: string;
  questions_total: number | null;
  questions_recorded: number;
  questions_answered: number;
  questions_correct: number;

  // marks-based scoring. `accuracy` is marks_awarded / marks_total over the
  // WHOLE answer key, so unanswered questions count against it - the same
  // definition the end screen uses. See STATS_PAGE_DESIGN.md §0.1.
  marks_awarded: number;
  marks_total: number;
  /** 0..1, or null when the answer key is missing (never 0 in that case). */
  accuracy: number | null;
  /**
   * correct / ANSWERED - the old meaning of `accuracy`. Kept because
   * "when you commit, how often are you right" is a real question; it is just
   * not the headline number.
   */
  precision_when_answered: number | null;
  avg_time_per_question_ms: number | null;
}

export interface QuestionFlagsView {
  question_attempt_id: string;
  exam_attempt_id: string;
  // added to the view so it can be filtered per user and per subject.
  user_id: string;
  paper_id: PaperSchema;
  subject_code: SubjectCode;
  local_date: IsoDate;
  question_number: number;
  is_correct: boolean | null;
  confidence: number | null;
  time_spent_ms: number;
  median_time_ms: number;
  /** Fast, no eliminations, essentially no interaction. */
  is_guess: boolean;
  /** Confident and wrong - the questions a student will not think to revise. */
  is_overconfident: boolean | null;
  /** Unsure and right - wasted time, or exam anxiety. */
  is_underconfident: boolean | null;
}

export interface CalibrationPointView {
  user_id: string;
  /** 1..10, from width_bucket over confidence. */
  confidence_bucket: number;
  questions: number;
  mean_confidence: number;
  observed_accuracy: number;
  /** observed_accuracy - mean_confidence. Negative = overconfident. */
  calibration_gap: number;
}

export interface DailyActivityView {
  user_id: string;
  local_date: IsoDate;
  papers: number;
  total_time_ms: number | null;
  questions: number;
  correct: number;
}

// v_hour_of_day had no matching type. 24 bins of local-hour activity -
// the "peak solving hour" card, and the polar chart in the engagement section.
export interface HourOfDayView {
  user_id: string;
  /** 0..23, in the user's own timezone at the time of the attempt. */
  local_hour: number;
  papers: number;
  total_time_ms: number | null;
}

export interface SubjectStatsView {
  user_id: string;
  subject_code: SubjectCode;
  subject_name: string | null;
  attempts: number;
  // marks-weighted across the subject, not the mean of per-paper
  // percentages - a 10-mark paper must not count as much as a 40-mark one.
  marks_awarded: number;
  marks_total: number;
  accuracy: number | null;
  total_time_ms: number | null;
  last_attempt_at: IsoTimestamp | null;
  avg_confidence: number | null;
  avg_difficulty: number | null;
  avg_interest: number | null;
}

export interface TopicMasteryView {
  user_id: string;
  subject_code: SubjectCode;
  topic_id: string;
  topic_name: string;
  questions: number;
  correct: number;
  // marks-based, matching every other accuracy in the schema.
  marks_awarded: number;
  marks_total: number;
  accuracy: number | null;
  avg_time_ms: number | null;
}
