-- ==========================================================================
--
-- Per-question topic tagging, and the v_topic_mastery rewrite that reads it.
--
-- WHY NOT paper_answers.topic_id, WHICH ALREADY EXISTS
-- Two reasons, and either alone is enough.
--
--   1. paper_answers rows only exist once a paper has been SAT - the table is
--      populated by the answer-key cache and is foreign-keyed to
--      paper_answer_keys. There is nowhere to put a topic for a paper nobody
--      has opened yet, which is all but a handful of them. Topic data is not
--      a property of an attempt and should not wait on one.
--
--   2. topic_id is a single column, and 1.2% of the tagged questions carry
--      more than one topic - up to three on the catalogue papers, and up to
--      six across the wider scrape. A column cannot hold them, and picking one
--      arbitrarily would quietly discard the rest.
--
-- So topics are a link table keyed by paper and question, independent of
-- whether anyone has sat the paper.
--
-- WHERE THE DATA IS
-- supabase/seeds/03_topics.sql, generated by scripts/buildTopics.ts. It is a
-- seed and not a migration because topics.subject_code references subjects,
-- and subjects is seeded too (01_subjects.sql) - seeds run after migrations on
-- `supabase db reset`, so a data migration here would find an empty subjects
-- table. That does mean topic data, like subject data, does NOT travel with
-- `supabase db push`; both seeds have to be applied to a hosted project by
-- hand. That gap predates this migration and is unchanged by it.
-- ==========================================================================

create table if not exists question_topics (
  -- Deliberately NOT a foreign key to paper_answer_keys: see above. A paper is
  -- a naming convention that fetch-pdf resolves on demand, not a row we hold.
  paper_id        text not null,
  question_number smallint not null,
  topic_id        uuid not null references topics(id) on delete cascade,
  primary key (paper_id, question_number, topic_id)
);

-- The lookup v_topic_mastery does: given the questions of an attempt, find
-- their topics. The primary key already covers (paper_id, question_number);
-- this one serves the reverse, "which questions cover topic X".
create index if not exists idx_question_topics_topic on question_topics(topic_id);

-- --------------------------------------------------------------------------
-- v_topic_mastery, reading question_topics instead of paper_answers.topic_id.
--
-- Marks still come from paper_answers, which is where they live. A question
-- tagged with two topics contributes its full marks to BOTH: getting a
-- waves-and-superposition question wrong is evidence against both topics, and
-- splitting the mark between them would understate each. It does mean the
-- per-topic marks_total across a subject can exceed the paper's total, so read
-- this view per topic and never sum it back up into a subject score -
-- v_subject_stats is what answers that question.
-- --------------------------------------------------------------------------
create or replace view v_topic_mastery as
select
  ea.user_id,
  t.subject_code,
  t.id   as topic_id,
  t.name as topic_name,
  count(*)                              as questions,
  count(*) filter (where qa.is_correct) as correct,
  coalesce(sum(pa.marks) filter (where qa.is_correct), 0)::int      as marks_awarded,
  coalesce(sum(pa.marks), 0)::int                                   as marks_total,
  coalesce(sum(pa.marks) filter (where qa.is_correct), 0)::numeric
    / nullif(sum(pa.marks), 0)          as accuracy,
  avg(qa.time_spent_ms)::int            as avg_time_ms
from question_attempts qa
join exam_attempts ea   on ea.id = qa.exam_attempt_id
join paper_answers pa   on pa.paper_id = ea.paper_id
                       and pa.question_number = qa.question_number
join question_topics qt on qt.paper_id = ea.paper_id
                       and qt.question_number = qa.question_number
join topics t           on t.id = qt.topic_id
where ea.status = 'completed'
group by ea.user_id, t.subject_code, t.id, t.name;

-- `create or replace view` keeps the existing options, but state it anyway so
-- the guarantee is visible here rather than three migrations back.
alter view v_topic_mastery set (security_invoker = true);
grant select on v_topic_mastery to authenticated;

-- --------------------------------------------------------------------------
-- Reference data, same shape as topics: readable by any signed-in user, and
-- writable only by the migration that generates it.
-- --------------------------------------------------------------------------
alter table public.question_topics enable row level security;
create policy question_topics_read on public.question_topics
  for select to authenticated using (true);

grant select on public.question_topics to authenticated;
revoke insert, update, delete on public.question_topics from authenticated;

-- --------------------------------------------------------------------------
-- paper_answers.topic_id is now superseded. It was never populated - the
-- loader in src/constants/topicMap.ts had no data to load - so nothing is
-- lost, but leaving two places to look for a question's topic is how they
-- come to disagree.
-- --------------------------------------------------------------------------
drop index if exists idx_paper_answers_topic;
alter table public.paper_answers drop column if exists topic_id;
